# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Frontend

on:
  push:
    branches: [ "origin" ]
    paths:
      - 'front/**'
  pull_request:
    branches: [ "origin" ]
    paths:
      - 'front/**'

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build frontend
      working-directory: ./front
      run: npm i &&  npm run build --if-present
    - name: Launch tests and generate coverage
      working-directory: ./front
      run: npm test
    - name: Debug report generation
      run: ls -la ./front/test-results
    - name: Upload coverage
      uses: phoenix-actions/test-reporting@v8
      with:
        name: Karma Jasmine Tests
        path: front/test-results/test-results.xml
        reporter: java-junit
  
  docker:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/origin'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          file: build.Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKER_HUB_CLIENT_IMAGE_NAME}}:latest