name: SonarCloud Analysis

on:
  push:
    branches:
      - origin
  pull_request:
    branches:
      - origin

jobs:
  # backend:
  #   name: SonarCloud Backend Analysis
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Java
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'temurin'
  #         java-version: '17'

  #     - name: Cache Maven packages
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.m2/repository
  #         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-maven-

  #     - name: Compile and analyze backend with Maven
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       run: |
  #         cd back
  #         mvn clean verify sonar:sonar \
  #         -Dsonar.organization=lefclem \
  #         -Dsonar.host.url=https://sonarcloud.io \
  #         -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  frontend:
    name: SonarCloud Frontend Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd front && npm install

      - name: Build frontend
        run: cd front && npm run build

      - name: Test frontend and generate coverage
        run: cd front && npm test --coverage

      - name: Analyze Frontend with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
