name: SonarCloud Analysis

on:
  push:
    branches: ["origin"]
  pull_request:
    branches: ["origin"]

jobs:
  backend:
    name: SonarCloud - Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build & Analyze backend
        working-directory: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=lefclem_BobApp_Backend \
            -Dsonar.organization=lefclem \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN_BACK }}

  frontend:
    name: SonarCloud - Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps & run tests
        working-directory: front
        run: |
          npm install
          npm run build
          npm test

      - name: Analyze frontend
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
